# coding: utf-8

"""
    TTX.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ttx_py.models.player_partial_dto import PlayerPartialDto

class TestPlayerPartialDto(unittest.TestCase):
    """PlayerPartialDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlayerPartialDto:
        """Test PlayerPartialDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlayerPartialDto`
        """
        model = PlayerPartialDto()
        if include_optional:
            return PlayerPartialDto(
                id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                slug = '',
                twitch_id = '',
                url = '',
                avatar_url = '',
                credits = 56,
                portfolio = 56,
                value = 56,
                type = 'User'
            )
        else:
            return PlayerPartialDto(
                id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                slug = '',
                twitch_id = '',
                url = '',
                avatar_url = '',
                credits = 56,
                portfolio = 56,
                value = 56,
                type = 'User',
        )
        """

    def testPlayerPartialDto(self):
        """Test PlayerPartialDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
