# coding: utf-8

"""
    TTX.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ttx_py.models.link_discord_twitch_dto import LinkDiscordTwitchDto

class TestLinkDiscordTwitchDto(unittest.TestCase):
    """LinkDiscordTwitchDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkDiscordTwitchDto:
        """Test LinkDiscordTwitchDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkDiscordTwitchDto`
        """
        model = LinkDiscordTwitchDto()
        if include_optional:
            return LinkDiscordTwitchDto(
                access_token = '',
                twitch_id = ''
            )
        else:
            return LinkDiscordTwitchDto(
                access_token = '',
                twitch_id = '',
        )
        """

    def testLinkDiscordTwitchDto(self):
        """Test LinkDiscordTwitchDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
