# coding: utf-8

"""
    TTX.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ttx_py.models.twitch_user_dto import TwitchUserDto

class TestTwitchUserDto(unittest.TestCase):
    """TwitchUserDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TwitchUserDto:
        """Test TwitchUserDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TwitchUserDto`
        """
        model = TwitchUserDto()
        if include_optional:
            return TwitchUserDto(
                id = '',
                display_name = '',
                login = '',
                avatar_url = ''
            )
        else:
            return TwitchUserDto(
                id = '',
                display_name = '',
                login = '',
                avatar_url = '',
        )
        """

    def testTwitchUserDto(self):
        """Test TwitchUserDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
