# coding: utf-8

"""
    TTX.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ttx_py.models.discord_token_dto import DiscordTokenDto

class TestDiscordTokenDto(unittest.TestCase):
    """DiscordTokenDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiscordTokenDto:
        """Test DiscordTokenDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiscordTokenDto`
        """
        model = DiscordTokenDto()
        if include_optional:
            return DiscordTokenDto(
                access_token = '',
                link_token = '',
                twitch_users = [
                    ttx_py.models.twitch_user_dto.TwitchUserDto(
                        id = '', 
                        display_name = '', 
                        login = '', 
                        avatar_url = '', )
                    ]
            )
        else:
            return DiscordTokenDto(
                access_token = '',
                link_token = '',
                twitch_users = [
                    ttx_py.models.twitch_user_dto.TwitchUserDto(
                        id = '', 
                        display_name = '', 
                        login = '', 
                        avatar_url = '', )
                    ],
        )
        """

    def testDiscordTokenDto(self):
        """Test DiscordTokenDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
