# coding: utf-8

"""
    TTX.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ttx_py.api.sessions_api import SessionsApi


class TestSessionsApi(unittest.TestCase):
    """SessionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SessionsApi()

    def tearDown(self) -> None:
        pass

    def test_discord_callback(self) -> None:
        """Test case for discord_callback

        """
        pass

    def test_link_discord_twitch(self) -> None:
        """Test case for link_discord_twitch

        """
        pass

    def test_twitch_callback(self) -> None:
        """Test case for twitch_callback

        """
        pass


if __name__ == '__main__':
    unittest.main()
