# coding: utf-8

"""
    TTX.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ttx_py.api.creators_api import CreatorsApi


class TestCreatorsApi(unittest.TestCase):
    """CreatorsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CreatorsApi()

    def tearDown(self) -> None:
        pass

    def test_create_creator(self) -> None:
        """Test case for create_creator

        """
        pass

    def test_get_creator(self) -> None:
        """Test case for get_creator

        """
        pass

    def test_get_creator_transactions(self) -> None:
        """Test case for get_creator_transactions

        """
        pass

    def test_get_creators(self) -> None:
        """Test case for get_creators

        """
        pass


if __name__ == '__main__':
    unittest.main()
