# coding: utf-8

"""
    TTX.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ttx_py.api.players_api import PlayersApi


class TestPlayersApi(unittest.TestCase):
    """PlayersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlayersApi()

    def tearDown(self) -> None:
        pass

    def test_gamba(self) -> None:
        """Test case for gamba

        """
        pass

    def test_get_player(self) -> None:
        """Test case for get_player

        """
        pass

    def test_get_players(self) -> None:
        """Test case for get_players

        """
        pass

    def test_get_self(self) -> None:
        """Test case for get_self

        """
        pass


if __name__ == '__main__':
    unittest.main()
