# coding: utf-8

"""
    TTX.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ttx_py.models.create_transaction_dto import CreateTransactionDto

class TestCreateTransactionDto(unittest.TestCase):
    """CreateTransactionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTransactionDto:
        """Test CreateTransactionDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTransactionDto`
        """
        model = CreateTransactionDto()
        if include_optional:
            return CreateTransactionDto(
                creator = '',
                action = 'Buy',
                amount = 56
            )
        else:
            return CreateTransactionDto(
                creator = '',
                action = 'Buy',
                amount = 56,
        )
        """

    def testCreateTransactionDto(self):
        """Test CreateTransactionDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
