# coding: utf-8

"""
    TTX.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ttx_py.models.transaction_action import TransactionAction

class TestTransactionAction(unittest.TestCase):
    """TransactionAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionAction(self):
        """Test TransactionAction"""
        # inst = TransactionAction()

if __name__ == '__main__':
    unittest.main()
