# coding: utf-8

"""
    TTX.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ttx.api.ttx_client_api import TTXClientApi


class TestTTXClientApi(unittest.TestCase):
    """TTXClientApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TTXClientApi()

    def tearDown(self) -> None:
        pass

    def test_create_creator(self) -> None:
        """Test case for create_creator

        """
        pass

    def test_discord_callback(self) -> None:
        """Test case for discord_callback

        """
        pass

    def test_gamba(self) -> None:
        """Test case for gamba

        """
        pass

    def test_get_creator(self) -> None:
        """Test case for get_creator

        """
        pass

    def test_get_creator_transactions(self) -> None:
        """Test case for get_creator_transactions

        """
        pass

    def test_get_creators(self) -> None:
        """Test case for get_creators

        """
        pass

    def test_get_player(self) -> None:
        """Test case for get_player

        """
        pass

    def test_get_players(self) -> None:
        """Test case for get_players

        """
        pass

    def test_get_self(self) -> None:
        """Test case for get_self

        """
        pass

    def test_link_discord_twitch(self) -> None:
        """Test case for link_discord_twitch

        """
        pass

    def test_place_order(self) -> None:
        """Test case for place_order

        """
        pass

    def test_twitch_callback(self) -> None:
        """Test case for twitch_callback

        """
        pass


if __name__ == '__main__':
    unittest.main()
