# coding: utf-8

"""
    TTX.Api

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TimeStep(str, Enum):
    """
    TimeStep
    """

    """
    allowed enum values
    """
    MINUTE = 'Minute'
    FIVEMINUTE = 'FiveMinute'
    FIFTEENMINUTE = 'FifteenMinute'
    THIRTYMINUTE = 'ThirtyMinute'
    HOUR = 'Hour'
    DAY = 'Day'
    WEEK = 'Week'
    MONTH = 'Month'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TimeStep from a JSON string"""
        return cls(json.loads(json_str))


